apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: news-analysis
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_TOPIC: "news_stream"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: news-analysis
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
